[package]
name = "ik_geo_lib"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ik_geo_lib"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
ik-geo = { path = "../ik-geo-rust" }