# If anything in the ik_python or rust folders change on push, run the workflow in the ik_python folder
on:
  push:
    branches:
        - main
        - master
    paths:
      - 'ik_python/**'
      - 'rust/**'
  pull_request:
    branches:
        - main
        - master
    paths:
      - 'ik_python/**'
      - 'rust/**'
  workflow_dispatch:
defaults:
    run:
        working-directory: ik_python
jobs:
    linux:
        runs-on: ${{ matrix.platform.runner }}
        strategy:
          matrix:
            platform:
              - runner: ubuntu-latest
                target: x86_64
              - runner: ubuntu-latest
                target: x86
              - runner: ubuntu-latest
                target: aarch64
              - runner: ubuntu-latest
                target: armv7
              - runner: ubuntu-latest
                target: s390x
              - runner: ubuntu-latest
                target: ppc64le
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: '3.10'
          - name: Build wheels
            uses: PyO3/maturin-action@v1
            with:
              target: ${{ matrix.platform.target }}
              args: --release --out dist --find-interpreter
              sccache: 'true'
              manylinux: auto
              working-directory: ik_python
          - name: Upload wheels
            uses: actions/upload-artifact@v4
            with:
              name: wheels-linux-${{ matrix.platform.target }}
              path: ik_python/dist
    windows:
        runs-on: ${{ matrix.platform.runner }}
        strategy:
          matrix:
            platform:
              - runner: windows-latest
                target: x64
              - runner: windows-latest
                target: x86
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: '3.10'
              architecture: ${{ matrix.platform.target }}
          - name: Build wheels
            uses: PyO3/maturin-action@v1
            with:
              target: ${{ matrix.platform.target }}
              args: --release --out dist --find-interpreter
              sccache: 'true'
              working-directory: ik_python
          - name: Upload wheels
            uses: actions/upload-artifact@v4
            with:
              name: wheels-windows-${{ matrix.platform.target }}
              path: ik_python/dist
    
    macos:
        runs-on: ${{ matrix.platform.runner }}
        strategy:
          matrix:
            platform:
              - runner: macos-latest
                target: x86_64
              - runner: macos-14
                target: aarch64
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: '3.10'
          - name: Build wheels
            uses: PyO3/maturin-action@v1
            with:
              target: ${{ matrix.platform.target }}
              args: --release --out dist --find-interpreter
              sccache: 'true'
              working-directory: ik_python
          - name: Upload wheels
            uses: actions/upload-artifact@v4
            with:
              name: wheels-macos-${{ matrix.platform.target }}
              path: ik_python/dist
    
    sdist:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Build sdist
            uses: PyO3/maturin-action@v1
            with:
              command: sdist
              args: --out dist
              working-directory: ik_python
          - name: Upload sdist
            uses: actions/upload-artifact@v4
            with:
              name: wheels-sdist
              path: ik_python/dist
    test:
      runs-on: ubuntu-latest
      needs: [linux, windows, macos, sdist]
      steps:
        - uses: actions/checkout@v4
        - name: Download wheels
          uses: actions/download-artifact@v4
          with:
            name: wheels-*
            path: ik_python/dist
        - name: Test wheels
          run: |
            python -m pip install --upgrade pip
            python -m pip install ik_python/dist/*.whl
            python -m pip install numpy
            python ik_python/test/test.py
          continue-on-error: false
    checkifcontinueworks:
      runs-on: ubuntu-latest
      needs: [test]
      steps:
        - name: Check if continue-on-error works
          run: echo "This step should not run if the previous step fails"      
    release:
        name: Release
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/')
        needs: [test]
        steps:
          - uses: actions/download-artifact@v4
          - name: Publish to PyPI
            uses: PyO3/maturin-action@v1
            env:
              MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
            with:
              command: upload
              args: --non-interactive --skip-existing wheels-*/*
